### ISSUE TITLE
IDesktopWallpaper: empty device name in GetMonitorDevicePathAt

### ISSUE THREAD

**Issue by qligier** [matthiasblaesing/JNA-Demos#2]
Hi!

In IDesktopWallpaper, the call to `GetMonitorDevicePathAt` succeeds, but the wide string read from the pointer is an empty string. Then, calls to `SetWallpaper` affects all the monitors instead of a single one, as if we passed NULL. The other method calls seem to work as expected, return values are present.

I am using Windows 10 22H2 with two HDMI monitors.

What I have tried:

- Initializing the COM link with a mix of `COINIT_MULTITHREADED` or `COINIT_APARTMENTTHREADED`, and optionally `COINIT_DISABLE_OLE1DDE`.
- Passing a `WTypes.LPWSTR` or `WTypes.LPWSTR.ByReference`: it fails with _A null reference pointer was passed to the stub.(HRESULT: 800706f4)_.
- Running it with different JDKs (11, 17, 18).

What could cause such an issue? Thank you!

Edit: Output example:
```
                                        : bottom: 1440/ left: 0/ right: 2560/ top: 0
	c:\windows\web\wallpaper\theme1\img13.jpg (DWPOS_CENTER)
                                        : bottom: 1440/ left: 0/ right: 2560/ top: 0
	c:\windows\web\wallpaper\theme1\img13.jpg (DWPOS_CENTER)
```

**Comment by matthiasblaesing** [comment]
This is a pure publishing repository. Please use the JNA mailing list for questions. You should provide a minimal runnable sample to unterstand your problem matter.

https://groups.google.com/g/jna-users
